services:
  telegram:
    image: quangthaictc/telegram-bot
    build:
      context: ./telegram
      dockerfile: Dockerfile
    depends_on:
      - api
    env_file: .env
    container_name: quackwf-bot
    network_mode: "host"
    volumes:
      - ./network_config.yaml:/app/network_config.yaml
      - ./utils/logger_config.py:/app/utils/logger_config.py

  controller:
    image: quangthaictc/ryu-application
    build:
      context: ./controller
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ryu-app
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - ./utils/logger_config.py:/app/utils/logger_config.py

  api:
    image: quangthaictc/fastapi
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - controller
    env_file:
      - .env
    container_name: fastapi
    network_mode: "host"
    restart: always
    volumes:
      - ./network_config.yaml:/app/network_config.yaml
      - ./utils/logger_config.py:/app/utils/logger_config.py

  infrastructure:
    image: quangthaictc/infrastructure
    depends_on:
      - controller
    build:
      context: ./infra
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: mn-wifi
    privileged: true
    network_mode: "host"
    environment:
      #- DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # GUI Forwarding (X11)
      #- /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /sys:/sys
      - /lib/modules:/lib/modules
      - /sys/kernel/debug:/sys/kernel/debug
      - /var/run/netns:/var/run/netns:shared
      - ./network_config.yaml:/app/network_config.yaml
      - ./utils/logger_config.py:/app/utils/logger_config.py
    tty: true
    stdin_open: true

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loggings/loki-config.yaml:/etc/loki/local-config.yaml
    network_mode: host

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./loggings/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    network_mode: host

volumes:
  grafana_data:
