services:
  telegram:
    image: quangthaictc/telegram-bot
    build:
      context: ./telegram
      dockerfile: Dockerfile
    env_file: .env
    container_name: quackwf-bot
    network_mode: "host"

  controller:
    image: quangthaictc/ryu-application
    build:
      context: ./controller
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ryu-app
    network_mode: "host"
    tty: true
    stdin_open: true

  api:
    image: quangthaictc/fastapi
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi
    network_mode: "host"
    restart: always

  infrastructure:
    image: quangthaictc/infrastructure
    # depends_on:
    #  - controller
    build:
      context: ./infra
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: mn-wifi
    privileged: true
    network_mode: "host"
    environment:
      #- DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # GUI Forwarding (X11)
      #- /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /sys:/sys
      - /lib/modules:/lib/modules
      - /sys/kernel/debug:/sys/kernel/debug
      - /var/run/netns:/var/run/netns:shared
    tty: true
    stdin_open: true
