switches:
  - name: s1
    cls: OVSSwitch
    protocols: OpenFlow13

aps:
  - name: ap1
    vssid: HUFLIT-GV,HUFLIT-NV
    ssid: HUFLIT
    mode: g
    channel: 1
    cls: OVSAP
    protocols: OpenFlow13
  - name: ap2
    vssid: HUFLIT-GV,HUFLIT-NV
    ssid: HUFLIT
    mode: g
    channel: 1
    cls: OVSAP
    protocols: OpenFlow13
